package systemPD;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Collection;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * UserProfile generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "user_profile", catalog = "event_planner")
public class UserProfile implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPassword;
	private String fullName;
	private String userPhone;
	private String userEmail;
	private int userStatus;
	private Collection<Token> token;

	public UserProfile() {
	}

	public UserProfile(String userName, String userPassword, String fullName, String userPhone, String userEmail,
			int userStatus) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.fullName = fullName;
		this.userPhone = userPhone;
		this.userEmail = userEmail;
		this.userStatus = userStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	@XmlElement
	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_password", nullable = false, length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	@XmlElement
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "full_name", nullable = false, length = 50)
	public String getFullName() {
		return this.fullName;
	}

	@XmlElement
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "user_phone", nullable = false, length = 50)
	public String getUserPhone() {
		return this.userPhone;
	}

	@XmlElement
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_email", nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	@XmlElement
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_status", nullable = false)
	public int getUserStatus() {
		return this.userStatus;
	}

	@XmlElement
	public void setUserStatus(int userStatus) {
		this.userStatus = userStatus;
	}

	@XmlTransient
	@OneToMany
	@JoinColumn(name="user_id",  insertable=false, updatable=false)		
	public Collection<Token> getToken() {
		return token;
	}

	public void setToken(Collection<Token> token) {
		this.token = token;
	}
	
	public Boolean authorize(String password){
		return getUserPassword().equals(password);
	}
	
	public Boolean authorizeStatus(){
		if(getUserStatus()==0){
			return false;
		}else{
			return true;
		}
	}

}
