
// Generated Jul 28, 2017 6:32:55 PM by Hibernate Tools 4.3.1.Final
package eventPD;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Collection;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.Cascade;

import com.owlike.genson.annotation.JsonIgnore;

/**
 * ClientInfo generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "client_info", catalog = "event_planner")
public class ClientInfo implements java.io.Serializable {

	private Integer clientId;
	private String clientName;
	private String clientAddress;
	private String clientPhone;
	private String clientEmail;
	private Collection<EventInfo> eventinfo;
	
	public ClientInfo(){
		
	}

	
	public ClientInfo(String clientName, String clientAddress, String clientPhone, String clientEmail) {
		this.clientName = clientName;
		this.clientAddress = clientAddress;
		this.clientPhone = clientPhone;
		this.clientEmail = clientEmail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "client_id", unique = true, nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "client_name", nullable = false, length = 100)
	public String getClientName() {
		return this.clientName;
	}

	@XmlElement
	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "client_address", nullable = false, length = 100)
	public String getClientAddress() {
		return this.clientAddress;
	}

	@XmlElement
	public void setClientAddress(String clientAddress) {
		this.clientAddress = clientAddress;
	}

	@Column(name = "client_phone", nullable = false, length = 100)
	public String getClientPhone() {
		return this.clientPhone;
	}

	@XmlElement
	public void setClientPhone(String clientPhone) {
		this.clientPhone = clientPhone;
	}

	@Column(name = "client_email", nullable = false, length = 100)
	public String getClientEmail() {
		return this.clientEmail;
	}

	@XmlElement
	public void setClientEmail(String clientEmail) {
		this.clientEmail = clientEmail;
	}
	
	@XmlTransient
//	@OneToMany(mappedBy = "clientinfo")
	@OneToMany(mappedBy = "clientinfo", cascade = CascadeType.ALL, orphanRemoval = true)
	public Collection<EventInfo> getEventinfo() {
		return eventinfo;
	}

	public void setEventinfo(Collection<EventInfo> eventinfo) {
		this.eventinfo = eventinfo;
	}
	
}
