// default package
// Generated Jul 29, 2017 7:13:10 AM by Hibernate Tools 4.3.1.Final
package eventPD;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.owlike.genson.annotation.JsonDateFormat;

/**
 * EventInfo generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "event_info", catalog = "event_planner")
public class EventInfo implements java.io.Serializable {

	private Integer eventId;
	private String eventName;
	
	@JsonDateFormat("yyyy-MM-dd")
	private Date eventDate;
	private String eventVenue;
	private int eventGuestsize;
	private int eventTablesize;
	private int userId;
	private int eventEmptytable;
	private int clientId;
	private int eventCompleted;

	private ClientInfo clientinfo;


	public EventInfo() {
	}

	public EventInfo(String eventName, Date eventDate, String eventVenue, int eventGuestsize, int eventTablesize,
			int userId, int eventEmptytable, int clientId, int eventCompleted) {
		this.eventName = eventName;
		this.eventDate = eventDate;
		this.eventVenue = eventVenue;
		this.eventGuestsize = eventGuestsize;
		this.eventTablesize = eventTablesize;
		this.userId = userId;
		this.eventEmptytable = eventEmptytable;
		this.clientId = clientId;
		this.eventCompleted = eventCompleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "event_id", unique = true, nullable = false)
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "event_name", nullable = false, length = 50)
	public String getEventName() {
		return this.eventName;
	}

	@XmlElement
	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "event_date", nullable = false, length = 10)
	public Date getEventDate() {
		return this.eventDate;
	}

	@XmlElement
	public void setEventDate(Date eventDate) {
		System.out.println(eventDate);
		this.eventDate = eventDate;
	}

	@Column(name = "event_venue", nullable = false, length = 100)
	public String getEventVenue() {
		return this.eventVenue;
	}

	@XmlElement
	public void setEventVenue(String eventVenue) {
		this.eventVenue = eventVenue;
	}

	@Column(name = "event_guestsize", nullable = false)
	public int getEventGuestsize() {
		return this.eventGuestsize;
	}

	@XmlElement
	public void setEventGuestsize(int eventGuestsize) {
		this.eventGuestsize = eventGuestsize;
	}

	@Column(name = "event_tablesize", nullable = false)
	public int getEventTablesize() {
		return this.eventTablesize;
	}

	@XmlElement
	public void setEventTablesize(int eventTablesize) {
		this.eventTablesize = eventTablesize;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	@XmlElement
	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "event_emptytable", nullable = false)
	public int getEventEmptytable() {
		return this.eventEmptytable;
	}

	@XmlElement
	public void setEventEmptytable(int eventEmptytable) {
		this.eventEmptytable = eventEmptytable;
	}

	@Column(name = "client_id", nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	@XmlElement
	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	@Column(name = "event_completed", nullable = false)
	public int getEventCompleted() {
		return this.eventCompleted;
	}

	@XmlElement
	public void setEventCompleted(int eventCompleted) {
		this.eventCompleted = eventCompleted;
	}
	
	@ManyToOne 
	@JoinColumn(name="client_id",  insertable=false, updatable=false, nullable=false)
	public ClientInfo getClientinfo() {
		return clientinfo;
	}

	@XmlElement
	public void setClientinfo(ClientInfo clientinfo) {
		this.clientinfo = clientinfo;
	}

}
