// default package
// Generated Aug 9, 2017 11:25:19 PM by Hibernate Tools 4.3.1.Final
package eventPD;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Collection;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * GuestInfo generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "guest_info", catalog = "event_planner")
public class GuestInfo implements java.io.Serializable {

	private Integer id;
	private String guestFname;
	private int tableAssigned;
	private int eventId;
	private int guestId;
	private String guestLname;
	private Collection<SeatWith> seatwith;
	private Collection<NotseatWith> notseat;
	
	public GuestInfo() {
	}

	public GuestInfo(String guestFname, int tableAssigned, int eventId, int guestId, String guestLname) {
		this.guestFname = guestFname;
		this.tableAssigned = tableAssigned;
		this.eventId = eventId;
		this.guestId = guestId;
		this.guestLname = guestLname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "guest_fname", nullable = false, length = 50)
	public String getGuestFname() {
		return this.guestFname;
	}

	@XmlElement
	public void setGuestFname(String guestFname) {
		this.guestFname = guestFname;
	}

	@Column(name = "table_assigned", nullable = false)
	public int getTableAssigned() {
		return this.tableAssigned;
	}

	@XmlElement
	public void setTableAssigned(int tableAssigned) {
		this.tableAssigned = tableAssigned;
	}

	@Column(name = "event_id", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	@XmlElement
	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "guest_id", nullable = false)
	public int getGuestId() {
		return this.guestId;
	}

	@XmlElement
	public void setGuestId(int guestId) {
		this.guestId = guestId;
	}

	@Column(name = "guest_lname", nullable = false, length = 50)
	public String getGuestLname() {
		return this.guestLname;
	}

	@XmlElement
	public void setGuestLname(String guestLname) {
		this.guestLname = guestLname;
	}

	@OneToMany(mappedBy="guestinfo")
	public Collection<SeatWith> getSeatwith() {
		return seatwith;
	}

	@XmlElement
	public void setSeatwith(Collection<SeatWith> seatwith) {
		this.seatwith = seatwith;
	}

	@OneToMany(mappedBy="guest")
	public Collection<NotseatWith> getNotseat() {
		return notseat;
	}

	@XmlElement
	public void setNotseat(Collection<NotseatWith> notseat) {
		this.notseat = notseat;
	}

}
