// default package
// Generated Aug 9, 2017 11:02:06 PM by Hibernate Tools 4.3.1.Final
package eventPD;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * SeatWith generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "seat_with", catalog = "event_planner")
public class SeatWith implements java.io.Serializable {

	private Integer id;
	private int guestId;
	private int seatwithId;
	private int eventId;
	private GuestInfo guestinfo;
	
	public SeatWith() {
	}

	public SeatWith(int guestId, int seatwithId, int eventId) {
		this.guestId = guestId;
		this.seatwithId = seatwithId;
		this.eventId = eventId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "guest_id", nullable = false)
	public int getGuestId() {
		return this.guestId;
	}

	@XmlElement
	public void setGuestId(int guestId) {
		this.guestId = guestId;
	}

	@Column(name = "seatwith_id", nullable = false)
	public int getSeatwithId() {
		return this.seatwithId;
	}

	@XmlElement
	public void setSeatwithId(int seatwithId) {
		this.seatwithId = seatwithId;
	}

	@Column(name = "event_id", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	@XmlElement
	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@ManyToOne
	@JoinColumn(name="guest_id", referencedColumnName = "guest_id", insertable=false, updatable=false, nullable=false)
	public GuestInfo getGuestinfo() {
		return guestinfo;
	}

	@XmlElement
	public void setGuestinfo(GuestInfo guestinfo) {
		this.guestinfo = guestinfo;
	}

}
